### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by 007scorpio** [FilipeBorges1993/Booh-Botnet#4]
have followed all the steps in installing your app but to no avail. when i go to http://mydomain.com/createUser/{user}/{password}, it only download index.php file.

Please help

**Comment by FilipeBorges1993** [comment]
hummm i will need to check it ! you need to replace the {user} to the name
of the user, {password} for the password!


007scorpio <notifications@github.com> escreveu no dia quinta, 21/02/2019
à(s) 18:09:

**Comment by 007scorpio** [comment]
i did that... Your installation process is quite not easy... yet nice project anyway

**Comment by 007scorpio** [comment]
this time am on ubuntu 18

**Comment by FilipeBorges1993** [comment]
Humm the laravel instalation is working? Do you se the login page?

A quinta, 21/02/2019, 19:19, 007scorpio <notifications@github.com> escreveu:

**Comment by 007scorpio** [comment]
Thank you I have fixed it

**Comment by FilipeBorges1993** [comment]
You welcome !

007scorpio <notifications@github.com> escreveu no dia sexta, 22/02/2019
à(s) 12:37:
